### ISSUE TITLE
A JavaScript error occurred in the main process: QUOTA_EXCEEDED_ERR

### ISSUE THREAD

**Issue by dhiller** [Kilian/fromscratch#21]
OS: Linux Mint Cinnamon 17.3

When starting the application the following stacktrace is thrown:

```
A JavaScript error occurred in the main process

Uncaught Exception:
QUOTA_EXCEEDED_ERR: Unknown error.
    at JSONStorage.LocalStorage.setItem (/opt/FromScratch-linux-x64/resources/app.asar/node_modules/node-localstorage/LocalStorage.js:153:15)
    at JSONStorage.setItem (/opt/FromScratch-linux-x64/resources/app.asar/node_modules/node-localstorage/LocalStorage.js:266:44)
    at storeWindowState (/opt/FromScratch-linux-x64/resources/app.asar/main.js:92:24)
    at BrowserWindow.<anonymous> (/opt/FromScratch-linux-x64/resources/app.asar/main.js:97:7)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:169:7)
```

Main application window is black, no text is shown. After confirming the error message with the OK button, the application starts up and functions normally.

**Comment by Kilian** [comment]
sometimes, for example when fromscratch is incorrectly closed (such as when it crashes) the windowState file is corrupted and this caues the error. If you delete the `~/.fromscratch/windowstate` file then the error should no longer appear.

In the upcoming version, there is a fix to prevent this from happening: https://github.com/Kilian/fromscratch/commit/382ee42f2b581f4b9a92d623b7c80562d6c9ce5a
