### ISSUE TITLE
some functions not working

### ISSUE THREAD

**Issue by kakbit** [Kilian/fromscratch#5]
Thank you for a clean note book app!

Unfortunately I'm having trouble with some of the cmd/ctrl-functions.
First of I can't close the application with ctrl+w/q, I'm assuming that's meaning ctrl+w or ctrl+q though I also tried ctrl+w+q   On the other hand, why would I want to close it   :)
Then it is the "zoom in" that isn't working while the "zoom out" is working. Thankfully there is a "reset text size" that is working.
(btw there is a typo in the line about zoom; you've typed crl instead of ctrl)

I'm running the app on Linux 3.13.0-77-generic x86_64 Xubuntu 14.04.3

**Comment by Kilian** [comment]
Both `ctrl + q` and `ctrl + w` should work... strange. Does Xubuntu maybe overwrite them?

Are you doing `ctrl + shift + =` for zoom in? It's actually `ctrl + =` because I'm lazy. I'll make sure that a "true" `ctrl +` also works.

**Comment by kakbit** [comment]
ctrl + =?
Then it's just a typo in the readme or I have to put my glasses on :)
No, it says "cmd/crl +/-" in the readme file.

**Comment by Kilian** [comment]
That should fix the ctrl + issue. could you test with a git checkout whether ctrl+q or ctrl+w works there?

**Comment by kakbit** [comment]
Sorry, I'm getting a error when trying to run it from the github version:

 npm run hot-server

> FromScratch@1.0.1 hot-server /home/patric/git/fromscratch
> node server.js

sh: 1: node: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by Kilian** [comment]
Can you get node 4.x? nodejs.org :)

**Comment by kakbit** [comment]
Done!

npm run hot-server

> FromScratch@1.0.1 hot-server /home/patric/git/fromscratch
> node server.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/patric/git/fromscratch/server.js:2:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "hot-server"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! FromScratch@1.0.1 hot-server: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the FromScratch@1.0.1 hot-server script 'node server.js'.
npm ERR! This is most likely a problem with the FromScratch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls FromScratch
npm ERR! There is likely additional logging output above.

**Comment by Kilian** [comment]
did you do a npm install first?

**Comment by kakbit** [comment]
Now that's done but the ctrl + shift + = is still dead
The ctrl + w/q is working :)

**Comment by Kilian** [comment]
All commands work for me. There is also no chance that you have a slightly different keyboard layout?

**Comment by Kilian** [comment]
@kakbit any update/can you tell me if you have a different keyboard layout?

**Comment by Kilian** [comment]
closing this for lack of activity.
